### ISSUE TITLE
Mobile Plugin not working

### ISSUE THREAD

**Issue by zethis** [xataz/docker-rtorrent-rutorrent#11]
Hello The mobile plugin not working, i have a java exception at launch
here a screen: https://ufile.io/ficsd

Can you test it plz ?

**Comment by zethis** [comment]
Fixed by enable HTTPRPC in config/rutorrent/conf/plugins.ini
Set [httprpc]
enabled = yes

**Comment by xataz** [comment]
Hello,

I update plugins.ini
