### ISSUE TITLE
Lien incorrect avec rTorrent.

### ISSUE THREAD

**Issue by Rathorian** [xataz/docker-rtorrent-rutorrent#15]
Salut,

Je viens de mettre à jour l'image avec ta dernière version et ça ne fonctionne plus.

Dans ruTorrent j'ai : 
> Lien incorrect avec rTorrent. Vérifier qu'il est bien en cours d'exécution. Vérifier la configuration de $scgi_port et de $scgi_host dans config.php et scgi_port dans le fichier de configuration de rTorrent.

Et dans les logs : 
> 2018-06-20 19:00:02,118 INFO supervisord started with pid 2951
2018-06-20 19:00:03,120 INFO spawned: 'rtorrent' with pid 2954
2018-06-20 19:00:03,121 INFO spawned: 'nginx' with pid 2955
2018-06-20 19:00:03,122 INFO spawned: 'php7' with pid 2956
2018-06-20 19:00:03,661 INFO exited: rtorrent (exit status 255; not expected)
2018-06-20 19:00:04,775 INFO spawned: 'rtorrent' with pid 2968
2018-06-20 19:00:04,776 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-20 19:00:04,776 INFO success: php7 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-20 19:00:04,822 INFO exited: rtorrent (exit status 255; not expected)
2018-06-20 19:00:06,826 INFO spawned: 'rtorrent' with pid 2970
2018-06-20 19:00:06,866 INFO exited: rtorrent (exit status 255; not expected)
2018-06-20 19:00:09,871 INFO spawned: 'rtorrent' with pid 2972
2018-06-20 19:00:09,914 INFO exited: rtorrent (exit status 255; not expected)
2018-06-20 19:00:10,916 INFO gave up: rtorrent entered FATAL state, too many start retries too quickly

Tu es peut-être au courant ?

**Comment by zerpex** [comment]
+1, je suis revenu sur l'image précédente qui fonctionne en attendant !

**Comment by xataz** [comment]
Sans doute le changement de version de libtorrent et rtorrent, j'essai de regarder ça au plus vite.

**Comment by Rathorian** [comment]
Ok sa marche. Merci

**Comment by xataz** [comment]
Normalement c'est bon, j'ai testé rapidement, suite changement de version, y'a des clés dans le rtorrent.rc qui ont changer de nom.

**Comment by Rathorian** [comment]
Personnellement j'ai toujours le même problème avec la même erreur !

**Comment by Chiledog** [comment]
@Rathorian moi aussi. :(

**Comment by zerpex** [comment]
Je n'ai pas le temps de tester avant demain, mais vu l'explication donnée par @xataz , il me parait logique qu'il faille supprimer la conf de rtorrent pour que l'image la régénère. Non ?

**Comment by Rathorian** [comment]
Je voudrais pas trop dire de bêtise, mais j'ai des doutes.

Vu les changements apportés par @xataz , je ne vois pas trop l'utilité de régénérer la conf mais je me trompe peut-être !!!

**Comment by Rathorian** [comment]
En fait, quand on regarde le wiki de rakshasa pour le .rtorrent.rc , il y a beaucoup plus de changement....

https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template

**Comment by xataz** [comment]
@zerpex Exactement, car je ne la supprime pas au démarrage, au cas où des modifications avaient été apporté à la main.

**Comment by Rathorian** [comment]
@xataz J'ai pourtant modifié : 

```
use_udp_trackers = yes
peer_exchange = no
```

PAR 

```
trackers.use_udp.set = yes
protocol.pex.set = no
```

Mais comme je le disais, j'ai toujours la même erreur et rtorrent ne démarre pas.

**Comment by xataz** [comment]
Active les logs avec : 
```
log.open_file = "rtorrent", "/tmp/rtorrent.log"
log.add_output = "info", "rtorrent"
log.add_output = "critical", "rtorrent"
log.add_output = "error", "rtorrent"
log.add_output = "warn", "rtorrent"
log.add_output = "notice", "rtorrent"
log.add_output = "debug", "rtorrent"
```

Et regarde dedans, tu as peux être une autre clé qui merdouille

**Comment by Rathorian** [comment]
Voilà l'erreur que j'ai récupérer dans le conteneur : 

> rtorrent: Error in option file: ~/.rtorrent.rc:22: Command "system.method.set_key" does not exist.

Pourtant dans mon .rtorrent.rc j'ai bien : 

```
system.method.set_key=event.download.finished,filebot,"execute={/usr/local/bin/postdl,$d.get_base_path=,$d.get_name=,$d.get_custom1=}"
system.method.set_key=event.download.erased,filebot_cleaner,"execute=/usr/local/bin/postrm"
```

**Comment by xataz** [comment]
Ah merde, j'ai pas testé la version avec filebot, system.method.set_key ne doit plus exister maintenant

**Comment by xataz** [comment]
Apparemment maintenant, c'est juste `method.set_key`

**Comment by Rathorian** [comment]
@xataz Oui je viens de faire des tests.

Il faut supprimer les : 

> system.method.set_key

Et les remplacer par 

> method.set_key

**Comment by xataz** [comment]
Je vais tester en ajoutant se script : https://github.com/rakshasa/rtorrent/blob/master/doc/scripts/update_commands_0.9.sed

**Comment by Rathorian** [comment]
Pas mal du tout effectivement :)

**Comment by Rathorian** [comment]
Salut @xataz 

Je reviens vers toi pour savoir quand tu penses pouvoir mettre à jour l'image ?
Rien ne presse vraiment, c'est juste histoire de savoir.

Merci

**Comment by Rathorian** [comment]
Avec la configuration actuelle, même si rtorrent se lance, filebot ne fonctionne pas.
Il n'a pas été lancé après le téléchargement d'un film et n'apparait donc pas sur Emby.

**Comment by xataz** [comment]
J'ai testé le fichier sed fourni, mais je sais pas pourquoi, il ne semble pas fonctionner.
Faut que je regarde de plus prêt, car il se peut que le format de method.set_key ait changé

**Comment by Rathorian** [comment]
J'ai aussi testé vite fait ce week-end le fichier sed, et comme toi, ça n'a pas fonctionné.

J'avais pas pensé au format de method.set_key
C'est fort possible, oui.

**Comment by Rathorian** [comment]
Alors après quelques recherches, j'ai modifié le .rtorrent.rc avec les nouvelles commandes. Par contre, je n'ai pas le temps d'essayer ce soir, donc je le propose ici, si quelqu'un veut faire un test : 

```
network.scgi.open_port = 0.0.0.0:5000

encoding.add = utf8
network.port_range.set = 49196-49196
network.port_random.set = no
pieces.hash.on_completion.set = no
directory.default.set = /data/torrents
session.path.set = /data/.session
protocol.encryption.set = allow_incoming, try_outgoing, enable_retry
trackers.use_udp.set = yes
dht.mode.set = disable
protocol.pex.set = no

throttle.min_peers.normal.set = 1
throttle.max_peers.normal.set = 100
throttle.min_peers.seed.set = 1
throttle.max_peers.seed.set = 50
throttle.max_uploads.set = 15

execute2 = {sh,-c,/usr/bin/php /nginx/www/html/torrent/php/initplugins.php torrent &}
schedule2 = watch_directory,1,1,"load_start=/data/.watch/*.torrent"
schedule2 = untied_directory,5,5,"stop_untied=/data/.watch/*.torrent"
schedule2 = espace_disque_insuffisant,1,30,close_low_diskspace=500M

method.set_key=event.download.finished,filebot,"execute2={/usr/local/bin/postdl,$d.base_path=,$d.name=,$d.custom1=}"
method.set_key=event.download.erased,filebot_cleaner,"execute2=/usr/local/bin/postrm"
```

**Comment by PixiBixi** [comment]
Lancez rtorrent à la mano dans le container et vous verrez qu'il y a des logs d'erreur concernant method.set_key

**Comment by Rathorian** [comment]
Justement, ça a été corrigé normalement !

**Comment by PixiBixi** [comment]
euh pas avec ton .rtorrent.rc que je vois en tout cas

**Comment by silkyclouds** [comment]
problème toujours présent après avoir modifié system.method.set.key en method.set.key. 

Je repasse a la version précédente...

Tu nous préviens quand le souci sera réglé?

**Comment by Rathorian** [comment]
@silkyclouds Essai avec mon .rtorrent.rc si tu as la possibilité : 

```
network.scgi.open_port = 0.0.0.0:5000

encoding.add = utf8
network.port_range.set = 49196-49196
network.port_random.set = no
pieces.hash.on_completion.set = no
directory.default.set = /data/torrents
session.path.set = /data/.session
protocol.encryption.set = allow_incoming, try_outgoing, enable_retry
trackers.use_udp.set = yes
dht.mode.set = off
protocol.pex.set = no

throttle.min_peers.normal.set = 1
throttle.max_peers.normal.set = 100
throttle.min_peers.seed.set = 1
throttle.max_peers.seed.set = 50
throttle.max_uploads.set = 15

execute2 = {sh,-c,/usr/bin/php /nginx/www/html/torrent/php/initplugins.php torrent &}
schedule2 = watch_directory,1,1,"load_start=/data/.watch/*.torrent"
schedule2 = untied_directory,5,5,"stop_untied=/data/.watch/*.torrent"
schedule2 = espace_disque_insuffisant,1,30,close_low_diskspace=500M

method.set_key=event.download.finished,filebot,"execute2={/usr/local/bin/postdl,$d.base_path=,$d.name=,$d.custom1=}"
method.set_key=event.download.erased,filebot_cleaner,"execute2=/usr/local/bin/postrm"
```

**Comment by silkyclouds** [comment]
je viens de le faire, par contre a chaque démarrage de rtorrent j'ai un très très long moment de démarrage car il met une plomber a appliquer les permissions. je te tiens au courant quand ça aura démarré.

**Comment by silkyclouds** [comment]
on a avancé la dessus ? @Rathorian , tu as mis ton fichier de conf à jour ? tu as pu tester ? 
Sinon, seul moyen est de downgrade ? car bon avoir rtorrent down depuis des jours c'est pas super... ;)

**Comment by Rathorian** [comment]
Non, je n'ai pas pris le temps d'essayer. Par contre oui, je te conseil de recréer une image avant tout les changements concernant la version 0.9.7/0.13.7 le temps de corriger tout ça.

**Comment by silkyclouds** [comment]
ouais sauf que je la recrée comment exactement ? 
j'utilise celle-ci :     image: xataz/rtorrent-rutorrent:latest-filebot
je remplace ça par quoi pour me débarrasser de celle qui ne marche pas et la remplacer par l'ancienne ?

**Comment by Rathorian** [comment]
@silkyclouds Si tu as supprimé l'ancienne image (celle qui fonctionnait), tu va devoir cloner le repos de xataz sur ton serveur, créer une nouvelle branche sur le dernier commit qui fonctionnait bien en version 0.9.6/0.13.6 puis build l'image....

Sinon, j'ai réussi à faire fonctionner la dernière version de rtorrent-rutorrent:filebot mais j'ai toujours un problème avec filebot qui ne s’exécute pas après le téléchargement d'un film. Je suis dans l'obligation de lancer filebot à la main dans le conteneur....

Voici le .rtorrent.rc : 
```
network.scgi.open_port = 0.0.0.0:5000

encoding.add = utf8
network.port_range.set = 49185-49185
network.port_random.set = no
pieces.hash.on_completion.set = no
directory.default.set = /data/torrents
session.path.set = /data/.session
protocol.encryption.set = allow_incoming, try_outgoing, enable_retry
trackers.use_udp.set = yes
dht.mode.set = disable
protocol.pex.set = no

throttle.min_peers.normal.set = 1
throttle.max_peers.normal.set = 100
throttle.min_peers.seed.set = 1
throttle.max_peers.seed.set = 50
throttle.max_uploads.set = 15

execute2 = {sh,-c,/usr/bin/php /nginx/www/html/torrent/php/initplugins.php torrent &}
schedule2 = watch_directory,1,1,"load.start=/data/.watch/*.torrent"
schedule2 = untied_directory,5,5,"stop_untied=/data/.watch/*.torrent"
schedule2 = espace_disque_insuffisant,1,30,close_low_diskspace=500M

method.set_key=event.download.finished,filebot,"execute2={/usr/local/bin/postdl,$d.base_path=,$d.name=,$d.custom1=}"
method.set_key=event.download.erased,filebot_cleaner,"execute2=/usr/local/bin/postrm"
#system.method.set_key=event.download.finished,filebot,"execute={/usr/local/bin/postdl,$d.get_base_path=,$d.get_name=,$d.get_custom1=}"
#system.method.set_key=event.download.erased,filebot_cleaner,"execute=/usr/local/bin/postrm"
```

Obligé de laisser "system.method.set_key" commenté puisque à chaque lancement du conteneur il le rajoute automatiquement, il faudrait modifier sa dans le Dockerfile.

**Comment by silkyclouds** [comment]
ça tourne, sauf que pour je ne sais quelle raison maintenant il ne voit plus du tout mes torrents en seed. pourtant c'est bien le bon dossier qui est renseigné...

@xataz une mise a jour qui règle le souci prévue ?

**Comment by xataz** [comment]
Désolé, j'ai laissé pas mal trainer, j'essai de corriger ce soir au plus tard.

**Comment by silkyclouds** [comment]
super timing car je suis entrain de migrer vers un nouveau serveur ! cool !

**Comment by silkyclouds** [comment]
une petite build en vue ? :)

**Comment by xataz** [comment]
Bon, j'ai plus d'erreur, j'ai un script de migration automatique, mais par contre, je n'arrive pas a faire fonctionner filebot, je ne comprends pas trop pourquoi

**Comment by xataz** [comment]
J'ai l'impression que l'event n'est pas pris en compte, y'a rien dans les logs qui l'indique.

**Comment by xataz** [comment]
Normalement c'est bon, à tester

**Comment by xataz** [comment]
C'est good, ma migration à fonctionné. Par contre si vous avez des configurations perso, il faudra les remettres, l'ancien fichier .rtorrent.rc est sauvegardé en .rtorrent.rc.old

**Comment by silkyclouds** [comment]
Génial je test ça aujourd’hui et je te tiens au courant.

**Comment by Rathorian** [comment]
Je test aussi ce soir.

En tout cas merci à toi @xataz car moi j'ai fait mon maximum avec mes compétences.

**Comment by silkyclouds** [comment]
2018-07-05 07:48:21,164 INFO spawned: 'rtorrent' with pid 115
2018-07-05 07:48:21,500 INFO exited: rtorrent (exit status 255; not expected)
2018-07-05 07:48:24,504 INFO spawned: 'rtorrent' with pid 119
2018-07-05 07:48:24,853 INFO exited: rtorrent (exit status 255; not expected)
2018-07-05 07:48:25,854 INFO gave up: rtorrent entered FATAL state, too many start retries too quickly

nope...marche pas ici. 

voilà l'image en question: 

xataz/rtorrent-rutorrent   latest-filebot      f52114f6e774        5 hours ago         427MB

**Comment by Rathorian** [comment]
Tu auras peut-être des logs un peu plus intéressants dans /tmp/rutorrent.log

**Comment by xataz** [comment]
J'ai justement rajouter des logs, normalement y'a tout dans le /tmp/rtorrent.log

**Comment by PixiBixi** [comment]
Petit soucis bizarre

Si un .rtorrent.rc est existant, impossible de relancer le container, je suis bloqué sur l'étape de génération de conf 

```
=INF= 2018/07/05-16:07:36 Generate configuration ...
```

Par contre, si aucun .rtorrent.rc existe, tout est ok

**Comment by silkyclouds** [comment]
ouais j’ai eu le meme souci ça freez si t’as un rtorrent existant. 
par contre derrière j’ai un souci de droit. faut dire que je lance mon conteneur avec un GID et UID spécifique pour des raisons d’accès a un drive monté un peu exotique. 
Ce soir pas le temps mais j’investigue demain !

**Comment by Rathorian** [comment]
Je viens de tester en supprimant avant la mise à jour mon dossier config de rtorrent vu que les autres ont des soucis avec une conf existante. Donc aucun problème de mon côté, fonctionne parfaitement et filebot aussi.

Juste une petite erreur dans les logs sur un chown de /var/lib/nginx/run : 
```
Creating sdbx ... done
=INF= 2018/07/05-20:26:05 Create user torrent ...
=SUC= 2018/07/05-20:26:05 Create user torrent done
=INF= 2018/07/05-20:26:05 Generate configuration ...
=SUC= 2018/07/05-20:26:05 Generate configuration done
=INF= 2018/07/05-20:26:05 Install plowshare ...
=SUC= 2018/07/05-20:26:08 Install plowshare done
=INF= 2018/07/05-20:26:08 Apply permissions ...
chown: /var/lib/nginx/run: No such file or directory
=SUC= 2018/07/05-20:26:10 Apply permissions done
2018-07-05 20:26:11,531 INFO supervisord started with pid 2978
2018-07-05 20:26:12,533 INFO spawned: 'rtorrent' with pid 2981
2018-07-05 20:26:12,536 INFO spawned: 'nginx' with pid 2982
2018-07-05 20:26:12,538 INFO spawned: 'php7' with pid 2983
2018-07-05 20:26:13,901 INFO success: rtorrent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-05 20:26:13,901 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-05 20:26:13,901 INFO success: php7 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by silkyclouds** [comment]
bon les gars pour moi ça donne ça:

1. je stop rtorrent
2. j'efface le .rtorrent.conf qui se trouve dans /opt/docker/media/.rtorrent/rtorrent/
3. je relance rtorrent et je check les logs : 

=INF= 2018/07/06-10:52:07 Generate configuration ...
sed: /home/torrent/.rtorrent.rc: No such file or directory
/usr/local/bin/startup: line 165: can't create /home/torrent/.rtorrent.rc: Symbolic link loop
/usr/local/bin/startup: line 165: can't create /home/torrent/.rtorrent.rc: Symbolic link loop
=SUC= 2018/07/06-10:52:07 Generate configuration done

ensuite en faisant un ls dans /opt/docker/media/.rtorrent/rtorrent/ je vois effectivement un symlink:

.rtorrent.rc -> /config/rtorrent/.rtorrent.rc
qui plus est, ce fichier appartient dès lors a root...

pr contre impossible de cat ce fichier : 

cat: .rtorrent.rc: No such file or directory

et j'ai pas de dossier /config du tout si ce n'est dans le conteneur lui meme... 

Je suis paumé la...quelqu'un peut me dire comment régler ce souci ?

**Comment by Rathorian** [comment]
Tu pourrais nous montrer les lignes qui correspondent à tes volumes persistants dans le docker-compose.yml ?

Tu as 2 volumes persistants à indiquer normalement. Les dossiers /data et /config. La ou tu as monté ton /config, tu devrais voir de mémoire 4 dossiers, rtorrent, rutorrent, custom_themes, et custom_plugins. Ce sont ses répertoires qu'il faut supprimer.

**Comment by silkyclouds** [comment]
hello, 

   volumes:
      - '.rtorrent:/config'
      - '/home/meaning/downloads/torrents:/data’

et oui, dans mon dossier .rtorrent, j’ai bien ces 4 dossiers. Mais il me crée un symlink. je sais pas pourquoi. 

voilà le contenu complet du log : 

=INF= 2018/07/06-10:52:07 Create user torrent ...
=SUC= 2018/07/06-10:52:07 Create user torrent done
=INF= 2018/07/06-10:52:07 Generate configuration ...
sed: /home/torrent/.rtorrent.rc: No such file or directory
/usr/local/bin/startup: line 165: can't create /home/torrent/.rtorrent.rc: Symbolic link loop
/usr/local/bin/startup: line 165: can't create /home/torrent/.rtorrent.rc: Symbolic link loop
=SUC= 2018/07/06-10:52:07 Generate configuration done
=INF= 2018/07/06-10:52:07 Install plowshare ...
=SUC= 2018/07/06-10:52:08 Install plowshare done
=INF= 2018/07/06-10:52:08 Apply permissions …

Mais après il freez sur apply permissions…la je l’ai lancé il y’a quasiment une heure et ça n’avance pas… 

ah et, dans le conteneur si je lance un batch, je n’ai pas de log détaillés dans /tmp

sudo docker exec -ti rtorrent bash
bash-4.4# cd /tmp/
bash-4.4# ls -lah
total 8
drwxrwxrwt    1 root     root        4.0K Jul  6 10:52 .
drwxr-xr-x    1 root     root        4.0K Jul  5 10:06 ..

quid? :/

**Comment by xataz** [comment]
@silkyclouds J'ai apporté une petite modif, pourrais tu refaire un essai

**Comment by silkyclouds** [comment]
je re-pull?

**Comment by xataz** [comment]
Yep

**Comment by xataz** [comment]
@Rathorian Par contre pour le chown je ne comprends pas pourquoi il y a cette erreur, car j'ai une boucle qui liste tout les dossiers et fichiers où faut modifier le owner, donc normalement il devrait exister

**Comment by xataz** [comment]
L'application des permissions peut être assez long si tu utilises overlayfs pour la gestion des layers.

Si tu n'as pas de configuration custom, je t'invites à supprimer le fichier .rtorrent/rtorrent/.rtorrent.rc

**Comment by silkyclouds** [comment]
ben, dans mon cas il y’a un share nfs et un google drive illimité map dans mon dossier torrent…donc je pense que ça va juste durer une éternité. mais comme je lance rtorrent avec mon user et que mes drives ont déja les bonnes permissions, je peux pas simplement zapper cette étape ?

**Comment by Rathorian** [comment]
@xataz Je vois pas trop non plus, en même temps je peux pas me pencher dessus, je suis sur mon smartphone avec aucun PC à disposition.

Mais ce problème existe pour moi depuis l'ancienne version déjà, j'avais juste pas indiqué le problème avant.

**Comment by Rathorian** [comment]
@xataz Je viens de regarder pour le problème du chown.
Voici ce que retourne un "ls -all /var/lib/nginx" dans le conteneur : 
```
bash-4.4# ls -all /var/lib/nginx/
total 16
drwxr-x---    1 torrent  torrent         42 Jul  5 04:46 .
drwxr-xr-x    1 root     root            44 Jul  5 04:46 ..
drwxr-sr-x    1 torrent  torrent         36 Jul  5 04:46 html
lrwxrwxrwx    1 root     root            14 Jul  5 04:46 logs -> /var/log/nginx
lrwxrwxrwx    1 root     root            22 Jul  5 04:46 modules -> /usr/lib/nginx/modules
lrwxrwxrwx    1 root     root            10 Jul  5 04:46 run -> /run/nginx
lrwxrwxrwx    1 root     root            14 Jul  5 04:46 tmp -> /var/tmp/nginx
```

/run/nginx est en rouge, il n'existe pas dans ce répertoire....

**Comment by Rathorian** [comment]
Problème réglé.

Merci Xataz
