### ISSUE TITLE
GeoIP fonctionel sur build stable ?

### ISSUE THREAD

**Issue by ShagoY** [xataz/docker-rtorrent-rutorrent#17]
Bonjour :)

Je viens de passer sur l'image Xataz (Anciennement diameter/rtorrent-rutorrent), tout fonctionne pour le mieux (build stable) mais je ne comprends pas du tout pourquoi je n'ai pas la localisation d'ip (GeoIP)...

Le plugin est bien "chargé & activé" et j'ai même suivi ceci : https://github.com/Novik/ruTorrent/issues/1239 mais sans le moindre résultat :-/

Là je bloque complètement...

Merci d'avance.

**Comment by djerfy** [comment]
Hello,

J'ai récemment bossé sur la revue de cette image chez moi (prochainement publiée) avec d'autres features dont ce GeoIP. Il y a pas mal de dépendances à installer dans l'image.

Je proposerais directement une merge request ici bientôt.

++

**Comment by xataz** [comment]
Salut,

la modification de @djerfy a été mergé, c'est en cours de build.
Merci pour cette issue et pour la PR.

**Comment by djerfy** [comment]
Hello,

Le modèle est bien installé mais je viens juste de m'apercevoir qu'il n'est pas chargé (côté php). Je vais te refaire une MR avec cette légère modification du coup. Merci par avance ;)

++

**Comment by ShagoY** [comment]
Oui, j'ai bien la localisation maintenant, merci :)

**Comment by djerfy** [comment]
Yes c’est tout bon ;) merci
