### ISSUE TITLE
Problème avec le RPC

### ISSUE THREAD

**Issue by Greaky** [xataz/docker-rtorrent-rutorrent#20]
Hello,

Je n'arrive pas à intégrer Sonarr avec le conteneur rtorrent.
Il y a t'il une configuration particulière  à apporter en plus  du docker run ?

J'ai beau essayer de faire `curl localhost:5000/RPC` sur le conteneur lui même, j'obtiens l'erreur `curl: (52) Empty reply from server`

Merci!

**Comment by PixiBixi** [comment]
Plop

Configures Sonarr en scgi, ça devrait marcher. scgi://localhost:5000, quelque chose du genre

**Comment by xataz** [comment]
Salut,

Effectivement le port 5000 est le port du scgi, pour faire un curl, ce sera plutôt localhost:8080/RPC

**Comment by Greaky** [comment]
Je vais restart le conteneur avec l'image stable au lieu de latest, je vous tiens au jus.

**Comment by Greaky** [comment]
`
![image](https://user-images.githubusercontent.com/7680607/47111723-94c7ad80-d254-11e8-8d79-f0e0f8588884.png)
`
RIP :(

**Comment by Magicalex** [comment]
Je crois que tu t'y prends mal. Déjà donnes nous ton `docker-compose.yml`

**Comment by Greaky** [comment]
Yes, pas de problème, j"essaye évidemment avec Sonarr en 1er.

`   rtorrent-rutorrent:
        container_name: rtorrent-rutorrent
        restart: always
        environment: 
            - GID=1002
            - UID=1002
            - PORT_RTORRENT=6681
            - DHT_RTORRENT=on
        ports:
            - '6681:6681/udp'
            - '6681:6681'
            - '49161:49161'
        volumes:
            - './rtorrent/config:/config:rw'
            - './rtorrent/data:/data:rw'
        image: 'xataz/rtorrent-rutorrent:stable'
        labels:
            - "traefik.frontend.rule=Host:seedbox-k8.pault-host.pw"
            - "traefik.port=8080"
        networks:
        - k8_global_network
        - k8_front_network

    sonarr:
            container_name: sonarr
            restart: always
            environment:
                - TZ=Europe/London
                - PUID=1002
                - PGID=1002
            volumes:
                - '../data/Videos/Manga:/manga:rw'
                - '../data/Videos/Serie:/tv:rw'
                - './sonarr:/config:rw'
                - './rtorrent/data:/downloads:rw'
            image: 'linuxserver/sonarr:latest'
` 
Les infos de sonarr:
![image](https://user-images.githubusercontent.com/7680607/47112426-91352600-d256-11e8-8df9-919c1511bbcc.png)

PS : j'ai déja 3 sonarr connectés avec des containers rtorrent. Cet fois ci je voulais tester cet image :).

**Comment by Magicalex** [comment]
Dans un premier temps essayes : pour Host : scgi://rtorrent-rutorrent pour Port : 5000 et Url Path : / ou vide

si scgi fonctionne pas remplace dans Host : rtorrent-rutorrent par http://rtorrent-rutorrent

**Comment by Greaky** [comment]
`must be valid without http://` dans les 2 cas.
