### ISSUE TITLE
Ajoute de autodl-irssi ? 

### ISSUE THREAD

**Issue by silkyclouds** [xataz/docker-rtorrent-rutorrent#21]
Hello,

j'aurais vraiment besoin d'autodl-issi (plugin) mais je ne pense pas qu'il soit possible de l'ajouter dans ton docker ? 

Si possible, aurais-tu un tuto ? Et si pas possible, pourrais-tu éventuellement l'ajouter a une build ? 

Merci !!!

**Comment by xataz** [comment]
Salut,

J'ai ajouté le module php sockets, qui est nécessaire à autodl-irssi.
Par contre, ne connaissant pas ce plugin, je ne peux pas l'ajouter en dur dans l'image, mais il est possible de le mettre sans soucis.

Dans ton répertoire que tu as monté dans /config, il de suffit de créer un répertoire custom_plugins, et d'y mettre les plugins que tu veux dessus. Au démarrage le conteneur les prendras en compte

**Comment by silkyclouds** [comment]
Super!!! Merci! 

Raphael

**Comment by xataz** [comment]
Est-ce que tu as réussi à mettre le plugin en place ?

**Comment by PixiBixi** [comment]
Plop,

Pour ce plugin, il serait bon de faire un nouveau tag Docker et ne pas l'inclure dans l'image de base :-)

**Comment by djerfy** [comment]
> Plop,
> 
> Pour ce plugin, il serait bon de faire un nouveau tag Docker et ne pas l'inclure dans l'image de base :-)

Je pense pas qu'il est nécessaire de faire une nouvelle image incluant ce module. Il faut juste le mettre dans le dossier `custom_plugins` et il sera pris en charge. De cette manière libre à tout le monde d'utiliser tel ou tel module sans avoir X images à maintenir. Ici @xataz a simplement rajouter les dépendances pour l'utilisation.

**Comment by silkyclouds** [comment]
bon je vais essayer ce soir. je réinstalle la ta build. Par contre sans irssi ça ne marchera pas. tu sais le rajouter ?

**Comment by silkyclouds** [comment]
d'ailleurs xataz, une petite question. La build que j'ai testé pour autodl ne modifiat pas du tout les perms. 

C'est très emètant pour moi d'avoir applying persmissions car j'ai un gdrive avec pas mal de trucs dessus monté, et ça prends une plombe. 

Y'a pas moyen de ne pas appliquer les permissions a chaque démarrage ?

**Comment by Magicalex** [comment]
Pour irssi tu peux utiliser l'image docker officiel https://hub.docker.com/_/irssi/

**Comment by silkyclouds** [comment]
super je regarde ça demain ! la je tombe de fatigue ! ;) merci !!!

**Comment by xataz** [comment]
Je vais ajouter une option pour ne pas modifier les permissions des datas, tu n'es pas le premier à me remonter ceci

**Comment by silkyclouds** [comment]
Extra! Bon sinon sans irssi dans le conteneur ca va etre challenge je pense pour installer autodl irssi.

Raphael

**Comment by xataz** [comment]
J'ai regardé rapidement le plugin, effectivement ça risque d'être assez galère pour utiliser irssi à l'exterieur, car il n'y a pas de variable pour configurer l'adresse, il pointe automatiquement sur 127.0.0.1.
Il faudrait modifier manuellement le code : https://github.com/autodl-community/autodl-rutorrent/blob/master/getConf.php#L130

**Comment by silkyclouds** [comment]
arggg ça pue. :(

bon ben soit tu sais l'add a l'image (car en fait audo dl irssi c'est quand meme un plugin super fort utilisé, mis d'office dans les rtorrent de pas mal de monde), soit je devrai repasser au conteneur de xeroxmalf qui l'intègre. 

dis-moi ce que t'en penses. 

MErci !

**Comment by Magicalex** [comment]
`audo dl irssi c'est quand meme un plugin super fort utilisé` mouais, il existe des outils comme sickchill ou medusa bien plus puissant de autodl-irssi

**Comment by Magicalex** [comment]
Ouais mais tous les trackers n’ont pas de chan et de plus tu peux régler l’ntervalle de temps à chaque check

**Comment by xataz** [comment]
Surtout que ça semble pas trop compliqué à modifier.

Perso je suis pas fan de l'intégrer directement a l'image, car ça reste une utilisation spécifique
