### ISSUE TITLE
.rtorrent.rc reset à chaque création de conteneur

### ISSUE THREAD

**Issue by Magicalex** [xataz/docker-rtorrent-rutorrent#23]
A chaque recréation du conteneur il me crée un nouveau .rtorrent.rc
https://github.com/xataz/docker-rtorrent-rutorrent/blob/master/rootfs/usr/local/bin/startup#L138

**Comment by djerfy** [comment]
C'est ton fichier personnalisé qui est écrasé avec celui par défaut ?

**Comment by xataz** [comment]
Si je comprends bien, il te migre a chaque démarrage vers la version 0.9.7 ?

**Comment by Magicalex** [comment]
oui c'est ça

**Comment by xataz** [comment]
C'est bon j'ai trouvé le soucis, la bulette de ma part
Je pousse une modif
