### ISSUE TITLE
Utiliser le mode deamon de rtorrent 0.9.7

### ISSUE THREAD

**Issue by Magicalex** [xataz/docker-rtorrent-rutorrent#25]
plus de détails ici : https://github.com/rakshasa/rtorrent/wiki/Daemon_Mode

et d'ajouter des options au démarrage pour plus de sécurité
```
  -D                Disable deprecated commands
  -I                Disable intermediate commands
```
https://rtorrent-docs.readthedocs.io/en/latest/cookbook.html#the-rtorrent-command-line

**Comment by djerfy** [comment]
Le `rtorrent` est directement géré via `supervisord` et il faut que ça reste en foreground. Par contre ça peut être intéressant pour désactiver les deprecated commands mais bon à voir

**Comment by xataz** [comment]
J'ai testé l'option daemon mode, elle reste en foreground, donc c'est top.

Je viens de push une version avec tout ça
