### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by KillaKev** [xataz/docker-rtorrent-rutorrent#26]
When trying to use custom themes I was getting an error where the sym link was failing. After investigating it looks like the directory path in the startup is incorrect. Instead of being 

 `ln -s /config/custom_themes/${custom_theme} /var/www/html${WEBROOT}/theme/themes/${custom_theme}`

it should be

`ln -s /config/custom_themes/${custom_theme} /var/www/html${WEBROOT}/plugins/theme/themes/${custom_theme}`

**Comment by djerfy** [comment]
I just create a pull request #27 
See [documentation](https://github.com/Novik/ruTorrent/wiki/PluginTheme) for more details

Thanks @KillaKev

**Comment by xataz** [comment]
Thanks for PR,

@KillaKev Can you retry ?

**Comment by KillaKev** [comment]
Just updated my docker image and everything works perfectly now. Thanks!
