### ISSUE TITLE
Error with execute command in rtorrent.rc

### ISSUE THREAD

**Issue by lokiiiii** [xataz/docker-rtorrent-rutorrent#29]
Hello Xataz,
I just updated my image this morning and it seems there is an issue:
When starting my container, I got an error:

`rtorrent: Error in option file: ~/.rtorrent.rc:18: Command "execute" does not exist.`

My rtorrent.rc didn't change recently:

`scgi_port = 0.0.0.0:5000
encoding_list = UTF-8
port_range = 49184-49184
port_random = no
check_hash = no
directory = /data/rutorrent/downloading
session = /data/.session
encryption = require,require_RC4,allow_incoming,try_outgoing
trackers.use_udp.set = yes
dht = off
protocol.pex.set = no
min_peers = 1
max_peers = 100
min_peers_seed = 1
max_peers_seed = 50
max_uploads = 15

execute = {sh,-c,/usr/bin/php7 /var/www/torrent/php/initplugins.php torrent &}
schedule = watch_directory_1,1,1,"blablabla"
schedule = watch_directory_2,1,1,"blablabla"
schedule = watch_directory_3,1,1,"blablabla"
`
Do you have an idea ?
Thanks :)

**Comment by Magicalex** [comment]
Update your configuration for rtorrent 0.9.7

**Comment by lokiiiii** [comment]
i'm sorry i can't find infos about these changes in rtorrent.rc 
did you mind indictates me where to find these modifications ?
Thanks :)
