### ISSUE TITLE
[ISSUE] Plowshare ?

### ISSUE THREAD

**Issue by PixiBixi** [xataz/docker-rtorrent-rutorrent#3]
Hello,

J'ai une ligne qui revient en boucle dans mes logs et de manière très très fréquente : 

```
WARNING: directory already exists! Do a git pull.
plowmod: adding legacy (default) repository: https://github.com/mcrapet/plowshare-modules-legacy.git
- installing new directory: /home/torrent/.config/plowshare/modules.d/legacy.git
```

Si tu pouvais regarder o/

BXT

**Comment by silkyclouds** [comment]
je déterre ce post mais.y 'a-t-il églement moyen d'utiliser l'ui de rutorrent pour plowdown ? ou juste plowup ?
