### ISSUE TITLE
Probleme GEOIP depuis le commit 09ced5a ?

### ISSUE THREAD

**Issue by ShagoY** [xataz/docker-rtorrent-rutorrent#30]
Depuis les commits de Mar 29, 2019, le plugin GEOIP ne semble plus fonctionner correctement (Pays : Inconnu) sur tous les clients.
Pour info, les ip sont bien "résolu" mais il semble avoir un problème de lien avec la database de GeoLite2 ?

J'ai testé sur une installation "docker run -dt -p 8080:8080 xataz/rtorrent-rutorrent" => Même problème.

Bien à toi.

**Comment by djerfy** [comment]
@ShagoY Effectivement depuis le commit 09ced5a3f8e117d69ca5821c5cfbfe7f70a4f62a ou c'est passé sur GeoIP2.

@xataz Je pense que tu devrais revenir sur GeoIP (plus simple) car le nouveau ne semble pas encore au point avec rutorrent, lié aussi au plugin `GeoIP`.

**Comment by xataz** [comment]
Oui j'ai remarqué ça aussi.

Le problème c'est que je ne trouve plus les fichiers de geoIP, sur le site de maxmind, il n'y a plus que GeoIP 2

**Comment by xataz** [comment]
J'ai trouvé ceci :  https://github.com/Micdu70/geoip2-rutorrent, je testerai demain pour voir

**Comment by xataz** [comment]
En fait j'ai fait la modif et testé en directe dans le conteneur, pas encore testé, c'est en train de build. Surprise demain si ça marche.

**Comment by ShagoY** [comment]
@xataz Sauf erreur et selon [https://microbadger.com/images/xataz/rtorrent-rutorrent:latest](url)
Ton dernier commit n'a pas été build. Cela ne fonctionne pas ?

**Comment by xataz** [comment]
Oui j'ai remis en place le build automatique qui ne fonctionnais plus, Normalement c'est bon.

J'ai juste un bug sur un plugin, je comprend pas trop pourquoi

**Comment by xataz** [comment]
Normalement c'est Ok, peux tu me le confirmer ?

**Comment by ShagoY** [comment]
@xataz Le flag est bien revenu, merci !
