### ISSUE TITLE
Env variable for DHT ?

### ISSUE THREAD

**Issue by PixiBixi** [xataz/docker-rtorrent-rutorrent#6]
Plop

Peux-tu faire une variable d'env pour le DHT please ?

A+

BXT

**Comment by xataz** [comment]
Je regarde ça se soir si j'ai le temps

**Comment by PixiBixi** [comment]
Merci ! :)

**Comment by PixiBixi** [comment]
Hello, pense à moi ! :)

**Comment by xataz** [comment]
C'est fait (enfin ^^) !!!

J'ai ajouté une variable DHT_RTORRENT

**Comment by PixiBixi** [comment]
Merci ! xD
