### ISSUE TITLE
Setup fileshare

### ISSUE THREAD

**Issue by PixiBixi** [xataz/docker-rtorrent-rutorrent#7]
Hello !

Est-ce que tu peux setup fileshare par defaut stp ? 

Pour cela, voici ce que j'ai du faire (Globalement c'est suivre le tuto de ex_rat (Je pense que tu peux modifier le fichier share.php pour que ça aille mieux)

Il faut déjà que tu créé un folder dans /config/rutorrent/conf/users/ avec le nom de l'user (Peut être avec une variable d'env ? :P) (C'est le share.php qui exige ça, on peut peut être le tweak ??)

Puis dans ce folder, il faut que tu fasses un config.php basique : 

```php
<?php
$topDirectory = '/data';
$scgi_port = 5000;
$scgi_host = '127.0.0.1';
$XMLRPCMountPoint = '/RPC';
```

Et une petite modification au niveau de nginx : 

```
    location ^~ /share {
        root /var/www/html;
        location ~ \.php$ {
            fastcgi_index index.php;
            fastcgi_pass unix:/tmp/php-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include /etc/nginx/fastcgi_params;
        }
        satisfy any;
        allow all;
    }
```

Il faut du coup créer le dossier /var/www/html/share et faire un lien symbolique : 
```
ln -s /var/www/html/torrent/plugins/fileshare/share.php /var/www/html/share
```

Globalement c'est tout ce que j'ai fait me semble :) 

PS: J'ai oublié, il faut configurer l'URL dans conf.php du plugin fileshare :)

**Comment by xataz** [comment]
Désolé pour le temps de réponse.

Le mieux serait que tu me fasse une PR, n'utilisant pas ce plugin, je ne saurais bien faire les tests de bon fonctionnement.

**Comment by xataz** [comment]
Je clos l'issue, si tu veux tu pourras me faire un PR
